server:
  port: 8081

spring:
  application:
    name: BankApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/BankApplication_Db
    username: postgres
    password: user1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %5p [%t] --- %c{1}: %m%n"
  level:
    root: ERROR
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.exceed: DEBUG
